#!/bin/bash


#Funciones:
function enable_g729(){

    files=$(ls -1 /g729 | wc -l)
    filename=$(ls /g729)
    if [ "$files" = "1" ];then
        cp -rf /g729/$filename /usr/lib/asterisk/modules/codec_g729.so
    else 

        echo "Es imposible activar el codec g729, revise que solo exista un archivo con la libreria"
        exit 1
    fi


}



function check_nspbx(){


    echo "NSPBX"



}


function check_default(){

    astvar=$(ls -A  /var/lib/asterisk )
    astetc=$(ls -A /etc/asterisk )
    astspool=$(ls -A /var/spool/asterisk )

    if [ "$astvar" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-lib/* /var/lib/asterisk/
    fi

    if [ "$astetc" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-etc/* /etc/asterisk/
    fi

    if [ "$astspool" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-spool/* /var/spool/asterisk/
        chown -R asterisk.asterisk /var/spool/asterisk
    fi

}

#Activar g729 si se necesita
if [ "$G729" = "YES" ];then
    enable_g729
fi


#Verificar si existen los archivos por defecto 
if [ "$MODE" = "NSPBX" ];then
    check_nspbx
else
    check_default
fi



#Inicio reparando permisos de archivos
chown -R asterisk.asterisk /etc/asterisk 
chown -R asterisk.asterisk /var/log/asterisk
chown -R asterisk.asterisk /var/lib/asterisk
chmod +x /usr/lib/asterisk/modules/*



#Proceso principal
exec /usr/sbin/asterisk -f -U asterisk -G asterisk