#!/bin/bash


#Funciones:
function enable_g729(){

    if [ -f /g729/codec_g729.so ];then
        if [ ! -f /opt/asterisk/lib/asterisk/modules/codec_g729.so ];then
            cp -rf /g729/codec_g729.so /opt/asterisk/lib/asterisk/modules/
            chmod +x /opt/asterisk/lib/asterisk/modules/codec_g729.so
        fi
    fi

}


function check_default(){

    astvar=$(ls -A  /var/lib/asterisk )
    astetc=$(ls -A /etc/asterisk )
    astspool=$(ls -A /var/spool/asterisk )

    if [ "$astvar" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-lib/* /var/lib/asterisk/
    fi

    if [ "$astetc" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-etc/* /etc/asterisk/
    fi

    if [ "$astspool" = "" ];then
        cp -rf /opt/asterisk/samples/asterisk-spool/* /var/spool/asterisk/
        chown -R asterisk.asterisk /var/spool/asterisk
    fi

}

#Activar g729 si se necesita
G729=(ls -A /g729)
if [ "$G729" != "" ];then
    enable_g729
fi  


#Verificar si existen los archivos por defecto 
check_default



#Inicio reparando permisos de archivos
chown -R asterisk.asterisk /etc/asterisk 
chown -R asterisk.asterisk /var/log/asterisk
chown -R asterisk.asterisk /var/lib/asterisk
chmod +x /usr/lib/asterisk/modules/*



#Proceso principal
exec /usr/sbin/asterisk -f -U asterisk -G asterisk